import importlib

_CONST = importlib.import_module(__name__)


class _Spec:
    def __repr__(self):
        return self.__class__.__qualname__


_SPEC_NAMES = [
    # archs
    "ARCH_32",
    "ARCH_64",
    # endians
    "ENDIAN_BIG",
    "ENDIAN_LITTLE",
    # versions
    "EI_VER_1",
    # Application Binary interfaces
    "ABI_SYSTEMV",
    "ABI_HPUX",
    "ABI_NETBSD",
    "ABI_LINUX",
    "ABI_HURD",
    "ABI_SOLARIS",
    "ABI_AIX",
    "ABI_IRIX",
    "ABI_FREEBSD",
    "ABI_TRU64",
    "ABI_MODESTO",
    "ABI_OPENBSD",
    "ABI_OPENVMS",
    "ABI_NONSTOP",
    "ABI_AROS",
    "ABI_FENIXOS",
    "ABI_CLOUDABI",
    "ABI_OPENVOS",
    # Object file types
    "ET_NONE",
    "ET_REL",
    "ET_EXEC",
    "ET_DYN",
    "ET_CORE",
    "ET_OS",
    "ET_PROC",
    # Instruction Architecture set (i wanna die)
    "ISA_RESERVED",
    "ISA_NONE",
    "ISA_ATT",
    "ISA_SPARC",
    "ISA_X86",
    "ISA_M68K",
    "ISA_M88K",
    "ISA_MCU",
    "ISA_I80860",
    "ISA_MIPS",
    "ISA_IBM370",
    "ISA_MIPS3K",
    "ISA_PARISC",
    "ISA_I80960",
    "ISA_POWERPC32",
    "ISA_POWERPC64",
    "ISA_S390",
    "ISA_IBMSPU",
    "ISA_NECV800",
    "ISA_FR20",
    "ISA_TRWRH32",
    "ISA_MRCE",
    "ISA_ARM",
    "ISA_DIGALPH",
    "ISA_SUPERH",
    "ISA_SPARC9",
    "ISA_STRICORE",
    "ISA_ARGORISC",
    "ISA_H8300",
    "ISA_H8300H",
    "ISA_H8S",
    "ISA_H8500",
    "ISA_IA64",
    "ISA_MIPSX",
    "ISA_COLDFIRE",
    "ISA_HC12",
    "ISA_FUMMA",
    "ISA_SPCP",
    "ISA_SRISC",
    "ISA_NDR1",
    "ISA_STARCORE",
    "ISA_ME16",
    "ISA_ST100",
    "ISA_TINYJ",
    "ISA_AMDX8664",
    "ISA_SDSP",
    "ISA_PDP10",
    "ISA_PDP11",
    "ISA_FX66",
    "ISA_ST9P",
    "ISA_ST7",
    "ISA_HC16",
    "ISA_HC11",
    "ISA_HC08",
    "ISA_HC05",
    "ISA_SVX",
    "ISA_ST19",
    "ISA_VAX",
    "ISA_AXIS",
    "ISA_INF",
    "ISA_ELEM14",
    "ISA_LSI",
    "ISA_TMS320C6K",
    "ISA_MCST",
    "ISA_AARCH",  # or ArmV8
    "ISA_Z80",
    "ISA_RISCV",
    "ISA_BPF",
    "ISA_65C816",
    # Program Header Segment Types
    "PT_NULL",
    "PT_LOAD",
    "PT_DYNAMIC",
    "PT_INTERP",
    "PT_NOTE",
    "PT_SHLIB",
    "PT_PHDR",
    "PT_TLS",
    "PT_OS",
    "PT_PROC",
    # Section header types
    "SHT_NULL",
    "SHT_PROGBITS",
    "SHT_SYMTAB",
    "SHT_STRTAB",
    "SHT_RELA",
    "SHT_HASH",
    "SHT_DYNAMIC",
    "SHT_NOTE",
    "SHT_NOBITS",
    "SHT_REL",
    "SHT_SHLIB",
    "SHT_DYNSYM",
    "SHT_INIT_ARRAY",
    "SHT_FINI_ARRAY",
    "SHT_PREINIT_ARRAY",
    "SHT_GROUP",
    "SHT_SYMTAB_SHNDX",
    "SHT_NUM",
    "SHT_OS",
    # Section header flags
    "SHF_WRITE",
    "SHF_ALLOC",
    "SHF_EXECINSTR",
    "SHF_MERGE",
    "SHF_STRINGS",
    "SHF_INFO_LINK",
    "SHF_LINK_ORDER",
    "SHF_OS_NONCONFORMING",
    "SHF_GROUP",
    "SHF_TLS",
    "SHF_MASKOS",
    "SHF_MASKPROC",
    "SHF_ORDERED",
    "SHF_EXCLUDE",
    # Special section indexes
    "SHN_UNDEF",
    "SHN_RESERVE",
    "SHN_OS",
    "SHN_PROC",
    "SHN_ABS",
    "SHN_COMMON",
    "SHN_XINDEX",
    "SHN_INDEX",
    # Dynamic entry types
    "DT_NULL",
    "DT_NEEDED",
    "DT_PLTRELSZ",
    "DT_PLTGOT",
    "DT_HASH",
    "DT_STRTAB",
    "DT_SYMTAB",
    "DT_RELA",
    "DT_RELASZ",
    "DT_RELAENT",
    "DT_STRSZ",
    "DT_SYMENT",
    "DT_INIT",
    "DT_FINI",
    "DT_SONAME",
    "DT_RPATH",
    "DT_SYMBOLIC",
    "DT_REL",
    "DT_RELSZ",
    "DT_RELENT",
    "DT_PLTREL",
    "DT_DEBUG",
    "DT_TEXTREL",
    "DT_JMPREL",
    "DT_BIND_NOW",
    "DT_INIT_ARRAY",
    "DT_FINI_ARRAY",
    "DT_INIT_ARRAYSZ",
    "DT_FINI_ARRAYSZ",
    "DT_RUNPATH",
    "DT_FLAGS",
    "DT_ENCODING",
    "DT_PREINIT_ARRAY",
    "DT_PREINIT_ARRAYSZ",
    "DT_MAXPOSTAGS",
    "DT_SUNW_AUXILIARY",
    "DT_SUNW_RTLDINF",
    "DT_SUNW_FILTER",
    "DT_SUNW_CAP",
    "DT_SUNW_SYMTAB",
    "DT_SUNW_SYMSZ",
    "DT_SUNW_ENCODING",
    "DT_SUNW_SORTENT",
    "DT_SUNW_SYMSORT",
    "DT_SUNW_SYMSORTSZ",
    "DT_SUNW_TLSSORT",
    "DT_SUNW_TLSSORTSZ",
    "DT_SUNW_CAPINFO",
    "DT_SUNW_STRPAD",
    "DT_SUNW_CAPCHAIN",
    "DT_SUNW_LDMACH",
    "DT_SUNW_CAPCHAINENT",
    "DT_SUNW_CAPCHAINSZ",
    "DT_OS",
    "DT_VALRNGLO",
    "DT_CHECKSUM",
    "DT_PLTPADSZ",
    "DT_MOVEENT",
    "DT_MOVESZ",
    "DT_POSFLAG_1",
    "DT_SYMINSZ",
    "DT_SYMINENT",
    "DT_VALRNGHI",
    "DT_ADDRRNGLO",
    "DT_CONFIG",
    "DT_DEPAUDIT",
    "DT_AUDIT",
    "DT_PLTPAD",
    "DT_MOVETAB",
    "DT_SYMINFO",
    "DT_ADDRRNGHI",
    "DT_RELACOUNT",
    "DT_RELCOUNT",
    "DT_FLAGS_1",
    "DT_VERDEF",
    "DT_VERDEFNUM",
    "DT_VERNEED",
    "DT_VERNEEDNUM",
    "DT_SPARC_REGISTER",
    "DT_AUXILIARY",
    "DT_USED",
    "DT_FILTER",
    "DT_PROC",
]
for _i in _SPEC_NAMES:

    class _REPL(_Spec):
        __qualname__ = _i
        __name__ = _i

        def __init__(self, value=None):
            self.value = value

    setattr(_CONST, _i, _REPL())
